# Generated by Django 3.2.12 on 2022-03-31 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_list', models.CharField(max_length=200)),
                ('product_count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='mainlist',
            name='list_details',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='List.listdetail'),
        ),
    ]
