# Generated by Django 3.2.12 on 2022-03-31 12:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0002_auto_20220331_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainlist',
            name='list_details',
        ),
        migrations.AddField(
            model_name='listdetail',
            name='List_ID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='List.mainlist'),
        ),
        migrations.AlterField(
            model_name='listdetail',
            name='product_count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='listdetail',
            name='product_list',
            field=models.CharField(max_length=200, verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='mainlist',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
