# Generated by Django 3.2.12 on 2022-03-31 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0003_auto_20220331_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listdetail',
            name='List_ID',
        ),
        migrations.AddField(
            model_name='mainlist',
            name='list_details',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='List.listdetail'),
        ),
    ]
