# Generated by Django 3.2.12 on 2022-03-31 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0004_auto_20220331_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainlist',
            name='list_details',
        ),
        migrations.AddField(
            model_name='listdetail',
            name='ID_list',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='List.mainlist'),
        ),
    ]
