# Generated by Django 3.2.12 on 2022-03-31 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0006_auto_20220331_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainlist',
            name='ID_list',
        ),
    ]
