# Generated by Django 3.2.12 on 2022-03-31 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0007_remove_mainlist_id_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainlist',
            name='product_list',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='List.listdetail'),
        ),
    ]
