# Generated by Django 3.2.12 on 2022-04-02 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0013_alter_mainlist_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=15, verbose_name='Логин')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
            ],
        ),
        migrations.AlterField(
            model_name='listdetail',
            name='ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='List.mainlist'),
        ),
        migrations.AlterField(
            model_name='mainlist',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название листа'),
        ),
    ]
