# Generated by Django 3.2.12 on 2022-04-04 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0014_auto_20220402_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainlist',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='List.user'),
        ),
    ]
