# Generated by Django 3.2.12 on 2022-04-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0017_auto_20220406_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainlist',
            name='user_id',
        ),
    ]
