# Generated by Django 3.2.12 on 2022-04-06 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0018_remove_mainlist_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
