# Generated by Django 3.2.12 on 2022-04-06 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0019_createuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainlist',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='List.createuser'),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='password',
            field=models.CharField(max_length=20, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Логин'),
        ),
    ]
