# Generated by Django 3.2.12 on 2022-04-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0021_auto_20220406_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainlist',
            name='user_id',
        ),
    ]
