# Generated by Django 3.2.12 on 2022-04-06 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('List', '0022_remove_mainlist_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainlist',
            name='log_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
