# Generated by Django 3.2.12 on 2022-04-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0024_listdetail_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listdetail',
            name='user_id',
        ),
    ]
